name: provider_for_redux
description: Let's you use Provider with Redux. Uses AsyncRedux, the non-boilerplate version of Redux (https://pub.dev/packages/async_redux).
version: 2.0.00-nullsafety.1
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/provider_for_redux

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'

dependencies:
  async_redux: ^9.0.0-nullsafety.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.0-nullsafety.1
  provider: ^5.0.0-nullsafety.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
